### ISSUE TITLE
ncurses 6.0+20170401 Causes Crash on Exit

### ISSUE THREAD

**Issue by watersalesman** [lfos/calcurse#31]
Upgrading from ncurses 6.0+20170128 to 6.0+20170401 causes calcurse to crash when exiting. I tested this on two machines, both of which are Arch Linux. On exit, config.c gives an error about an unknown color in the configuration file. Trying to change the background color from the terminal default gives a segmentation fault. Below are pictures:
</br>

<img src="https://cloud.githubusercontent.com/assets/24920804/25437549/ba73e57e-2a64-11e7-8b75-491cdc41c055.png" height="350">

</br>

<img src="https://cloud.githubusercontent.com/assets/24920804/25437550/ba7adfbe-2a64-11e7-8a26-91ac17059c83.png" height="350">

**Comment by gilcu3** [comment]
I can confirm the same happens here (also archlinux BTW), something must have changed in ncurses colors, for now, not using colors works fine,
set variable 
appearance.theme=none 
in conf

**Comment by ralpheeee88** [comment]
@gilcu3 nice..thxs!

**Comment by lfos** [comment]
At least the error on exit is caused by a ncurses bug that is fixed in
the latest ncurses release. I will upgrade the Arch Linux ncurses
package soon.

**Comment by ralpheeee88** [comment]
@lfos  any progress?

**Comment by lfos** [comment]
I upgraded the ncurses package a couple of hours after I wrote that comment. It should be fixed with ncurses 6.0+20170429-1. Is you system up-to-date?

**Comment by ralpheeee88** [comment]
@gilcu3 https://i.imgur.com/0wUHD9E.png  still experiencing crash....if its just me the just ignore...

**Comment by modernrio** [comment]
I can confirm this problem still exists..using the latest ncurses version. (also archlinux)

`core/ncurses 6.0+20170527-1 [installed]
`

**Comment by leo-mao** [comment]
confirmed the crash here. http://i.imgur.com/tCPCn1S.png

>Linux Manjaro-Paradox 4.11.3-1-MANJARO #1 SMP PREEMPT Thu May 25 20:44:21 UTC 2017 x86_64 GNU/Linux

**Comment by lfos** [comment]
The crash experienced when changing colors in the menu should be fixed in master. Does anybody still experience crashes on exit (using current master and ncurses >=6.0+20170527-1)?

**Comment by modernrio** [comment]
The problem is fixed on my system. No crashes when changing to any of the colors.

With current master (commit `43cd40e`) and ncurses (version `6.0+20170527-1`) on Arch Linux

**Comment by lfos** [comment]
Fixed by commit 5722d2e.
